/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 09-Jun-2019 10:39:55
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 37
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB2\R2017a\extern\include\tmwtypes.h 
 */
//const int BL = 10;
//const char B[10] = {0.0051, -0.0000, -0.0419, 0.0000, 0.2885,  0.4968,  0.2885,  0.0000,  -0.0419, -0.0000, 0.0051};
